config/routes.rb
Notman::Application.routes.draw do
  resources :events

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :locations
  devise_for :users

  root :to => 'events#dashboard'

  match "/delayed_job" => DelayedJobWeb, :anchor => false

  

end

app/models/collection.rb
class Collection
    def update_data


	require 'net/http'
    User.where(:device_id != nil).each do |user|

      uri = URI.parse("http://api.reelyactive.com/devices/#{user.device_id.to_s}/location")
      http = Net::HTTP.new(uri.host, uri.port)
      request = Net::HTTP::Get.new(uri.request_uri)
      request["Accept"] = "application/json"
      response = http.request(request)
      json = JSON.parse(response.body)

      #Rails.logger.info(json.to_yaml)
      #Rails.logger.info("---------------")
      location_device_id = json['Device']['Location']['Decoders']['Decoder']['ID']
      user_device_id = json['Device']['ID']
      the_date = json['Device']['TimeStamp']

      user = User.find_by_device_id(user_device_id)
      location = Location.find_by_device_id(location_device_id)

      if user and location and the_date
        Event.create(location_id:location.id, user_id: user.id, the_date:the_date)
      else
        Rails.logger.info("Failure----------->" + json.to_yaml)
      end
	end

        self.delay(:run_at => 1.minute.from_now).update_data
    end

    def self.start_me_up
        new.update_data
    end
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :location_id, :the_date, :user_id, :user_id

  belongs_to :user
  belongs_to :location


def check_status

end

end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :name, :device_id, :id

  has_many :events
  has_many :users, :through => :events
end

app/models/team.rb
class Team < ActiveRecord::Base
	attr_accessible :name, :id

	has_many :users


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :id,
  	:first_name, :last_name, :nick_name, :team_id, :device_id
  # attr_accessible :title, :body

  belongs_to :team
  has_many :events
  has_many :locations, :through => :events

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController


def dashboard
    @events = Event.all


end



  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :the_date %><br />
    <%= f.date_select :the_date %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br />
    <%= f.number_field :location_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/dashboard.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>The date</th>
    <th>Location</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.the_date %></td>
    <td><%= event.location_id %></td>
    <td><%= event.user_id %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>The date</th>
    <th>Location</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.the_date %></td>
    <td><%= event.location_id %></td>
    <td><%= event.user_id %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>The date:</b>
  <%= @event.the_date %>
</p>

<p>
  <b>Location:</b>
  <%= @event.location_id %>
</p>

<p>
  <b>User:</b>
  <%= @event.user_id %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Notman</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :reely_receiver_id %><br />
    <%= f.text_field :reely_receiver_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Reely receiver</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @locations.each do |location| %>
  <tr>
    <td><%= location.name %></td>
    <td><%= location.reely_receiver_id %></td>
    <td><%= link_to 'Show', location %></td>
    <td><%= link_to 'Edit', edit_location_path(location) %></td>
    <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @location.name %>
</p>

<p>
  <b>Reely receiver:</b>
  <%= @location.reely_receiver_id %>
</p>


<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>